CREATE TABLE BD_AUTEUR(
 	ID_AUTEUR INTEGER(10) NOT NULL, PRIMARY KEY (ID_AUTEUR),
 	PSEUDO VARCHAR(100),
 	PRENOM VARCHAR(100),
 	NOM VARCHAR(100),
 	FLG_SCENAR CHAR(2147483647),
 	FLG_DESSIN CHAR(2147483647),
 	FLG_COLOR CHAR(2147483647),
	COMMENT VARCHAR(2147483647),
 	DTE_NAIS DATETIME,
 	DTE_DECES DATETIME,
 	NATIONALITE VARCHAR(15),
 	NOM_PSEUDO VARCHAR(100)
);

CREATE TABLE BD_COLLECTION(
 	ID_COLLECTION INTEGER(10) NOT NULL, PRIMARY KEY (ID_COLLECTION),
 	NOM VARCHAR(100),
 	ID_EDITEUR INTEGER(10)
);

CREATE TABLE BD_EDITEUR(
 	ID_EDITEUR INTEGER(10) NOT NULL, PRIMARY KEY (ID_EDITEUR),
 	NOM VARCHAR(100) NOT NULL,
 	URL_SITE VARCHAR(100)
);

CREATE TABLE BD_GENRE(
 	ID_GENRE INTEGER(10) NOT NULL, PRIMARY KEY (ID_GENRE),
 	LIBELLE VARCHAR(100) NOT NULL,
	ORIGINE VARCHAR(10) NOT NULL
);

CREATE TABLE BD_SERIE(
 	ID_SERIE INTEGER(10) NOT NULL, PRIMARY KEY (ID_SERIE),
 	NOM VARCHAR(100),
 	ID_GENRE INTEGER(10),
 	NOTE INTEGER(10),
 	FLG_FINI CHAR(2147483647),
 	NB_TOME INTEGER(10),
 	NB_NOTE INTEGER(10) NOT NULL,
 	TRI VARCHAR(3),
 	HISTOIRE VARCHAR(2147483647),
	FOREIGN KEY (ID_GENRE) REFERENCES BD_GENRE(ID_GENRE)
);

CREATE TABLE BD_TOME(
	ID_TOME INTEGER(10) NOT NULL, PRIMARY KEY (ID_TOME),
	TITRE VARCHAR(150),
 	NUM_TOME INTEGER(10),
	ID_SERIE INTEGER(10),
	DTE_PARUTION DATETIME,
	ID_GENRE INTEGER(10),
 	ID_EDITEUR INTEGER(10) NOT NULL,
 	ID_SCENAR INTEGER(10) NOT NULL,
 	ID_SCENAR_ALT INTEGER(10) NOT NULL,
 	ID_DESSIN INTEGER(10) NOT NULL,
 	ID_DESSIN_ALT INTEGER(10) NOT NULL,
 	ID_COLOR INTEGER(10) NOT NULL,
 	ID_COLOR_ALT INTEGER(10) NOT NULL,
 	ID_COLLECTION INTEGER(10),
 	FLG_INT CHAR(2147483647) NOT NULL,
 	FLG_TYPE INTEGER(10) NOT NULL,
 	URL_BDNET VARCHAR(50),
 	PRIX_BDNET FLOAT(17),
 	EAN VARCHAR(13),
 	ISBN VARCHAR(10),
 	MOYENNE FLOAT(17),
 	NB_VOTE INTEGER(10) NOT NULL,
 	HISTOIRE VARCHAR(2147483647),
 	IMG_COUV VARCHAR(100),
	FOREIGN KEY (ID_SERIE) REFERENCES BD_SERIE(ID_SERIE),
	FOREIGN KEY (ID_GENRE) REFERENCES BD_GENRE(ID_GENRE),
	FOREIGN KEY (ID_EDITEUR) REFERENCES BD_EDITEUR(ID_EDITEUR),
	FOREIGN KEY (ID_SCENAR) REFERENCES BD_AUTEUR(ID_AUTEUR),
	FOREIGN KEY (ID_SCENAR_ALT) REFERENCES BD_AUTEUR(ID_AUTEUR),
	FOREIGN KEY (ID_DESSIN) REFERENCES BD_AUTEUR(ID_AUTEUR),
	FOREIGN KEY (ID_DESSIN_ALT) REFERENCES BD_AUTEUR(ID_AUTEUR),
	FOREIGN KEY (ID_COLOR) REFERENCES BD_AUTEUR(ID_AUTEUR),
	FOREIGN KEY (ID_COLOR_ALT) REFERENCES BD_AUTEUR(ID_AUTEUR),
	FOREIGN KEY (ID_COLLECTION) REFERENCES BD_COLLECTION(ID_COLLECTION)
);

CREATE TABLE BD_EDITION(
 	ID_EDITION INTEGER(10) NOT NULL, PRIMARY KEY (ID_EDITION),
 	ID_TOME INTEGER(10),
 	FLG_DEFAULT CHAR(2147483647),
	ID_EDITEUR INTEGER(10),
 	ID_COLLECTION INTEGER(10),
 	DTE_PARUTION DATETIME,
 	EAN VARCHAR(13),
 	ISBN VARCHAR(10),
 	FLG_EO CHAR(1) NOT NULL,
 	FLG_TT CHAR(1) NOT NULL,
 	IMG_COUV VARCHAR(100),
 	COMMENT VARCHAR(2147483647),
 	USER_ID INTEGER(10),
 	PROP_DTE DATETIME,
 	PROP_STATUS INTEGER(10) NOT NULL,
 	VALIDATOR INTEGER(10),
 	VALID_DTE DATETIME,
	FOREIGN KEY (ID_TOME) REFERENCES BD_TOME(ID_TOME),
	FOREIGN KEY (ID_EDITEUR) REFERENCES BD_EDITEUR(ID_EDITEUR),
	FOREIGN KEY (ID_COLLECTION) REFERENCES BD_COLLECTION(ID_COLLECTION)
);


CREATE TABLE USERS_ALBUM(
 	ID_TOME INTEGER(10) NOT NULL,
 	ID_SERIE INTEGER(10),
 	ID_EDITEUR INTEGER(10),
 	ID_COLLECTION INTEGER(10),
 	ID_EDITION INTEGER(10) NOT NULL, PRIMARY KEY (ID_TOME,ID_EDITION),
 	ID_SCENAR INTEGER(10),
 	ID_DESSIN INTEGER(10),
 	ID_GENRE INTEGER(10),
 	FLG_PRET CHAR(2147483647),
 	NOM_PRET VARCHAR(100),
 	EMAIL_PRET VARCHAR(100),
 	FLG_DEDICACE CHAR(2147483647),
 	FLG_TETE CHAR(2147483647) NOT NULL,
 	COMMENT CHAR(2147483647),
 	NOTE INTEGER(3),
 	DATE_AJOUT DATETIME,
 	FLG_ACHAT CHAR(2147483647),
 	DATE_ACHAT DATETIME,
 	COTE FLOAT(17),
 	FLG_CADEAU CHAR(2147483647) NOT NULL
);

CREATE TABLE USERS_EXCLUSIONS(
 	ID_TOME INTEGER(10) NOT NULL,
 	ID_SERIE INTEGER(10) NOT NULL, PRIMARY KEY (ID_TOME,ID_SERIE)
);